### ISSUE TITLE
I18n-ize GMail Counter

### ISSUE THREAD

**Issue by EliaCereda** [EliaCereda/GMail-Counter#6]
i18n-ize and translate GMail Counter in English, German and Italian.

Volunteers can offer themselves to translate in other languages.

**Comment by ghost** [comment]
I'll do german.

**Comment by EliaCereda** [comment]
@frankkohlhepp: added some more i18n strings (commits 0ea26bc22b, 457086e0ef and 16ad6967c9)

**Comment by EliaCereda** [comment]
@frankkohlhepp: added some more strings in settings/i18n.js (commit 64fe8a2a14)
