### ISSUE TITLE
Support for Safari in Wine on Pi

### ISSUE THREAD

**Issue by WarheadsSE** [EliaCereda/GMail-Counter#8]
Can you confirm this work with Safari for Windows on Wine on a Raspberry Pi running linux Pi?

**Comment by EliaCereda** [comment]
I wouldn't know... Actually I don't even have a GUI installed on my Pi.
But if Safari runs on Wine then Gmail Counter should run too.

-- Elia Cereda

2014-04-01 16:37 GMT+02:00 WarheadsSE notifications@github.com:
